export enum ReportColumnType {
  type_Of_Testing = 'string',
  scope = 'string',
  header_Image = 'string',
  header_Text = 'string',
  footer_Text = 'string',
  application_Name = 'string',
  assessment_Type = 'string',
  company_Name = 'string',
  company_Logo = 'string',
  severity = 'string',
  vulnerability = 'string',
  affectedScope = 'string',
  description = 'string',
  observation = 'string',
  test_Details = 'string',
  remediation = 'string',
  references = 'string',
}
